# Generated by Django 4.0.3 on 2022-04-09 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=150)),
                ('jobDescription', models.CharField(max_length=500)),
                ('necessarySkills', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserAppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='jobs.job')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
